name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Nightmarecheckout
        uses: actions/checkout@master
        with:
          token: ${{secrets.API_KEY}}
          repository: GordonArscott/SECRETS_OCT_V1 #This is where we are going to grab the repo from to us
          path: tests
      #checkout secret tests
      - uses: education/autograding@v1
